/*
 * generated by Xtext 2.20.0
 */
package de.tubs.isf.guido.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DslRuntimeModule extends AbstractDslRuntimeModule {
}
