/**
 * generated by Xtext 2.20.0
 */
package de.tubs.isf.guido.dsl.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constructs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tubs.isf.guido.dsl.dsl.Constructs#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getConstructs()
 * @model
 * @generated
 */
public interface Constructs extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' attribute list.
   * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getConstructs_Elements()
   * @model unique="false"
   * @generated
   */
  EList<String> getElements();

} // Constructs
