/**
 * generated by Xtext 2.19.0
 */
package de.tubs.isf.guido.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constructs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tubs.isf.guido.dsl.dsl.Constructs#getElement <em>Element</em>}</li>
 *   <li>{@link de.tubs.isf.guido.dsl.dsl.Constructs#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getConstructs()
 * @model
 * @generated
 */
public interface Constructs extends EObject
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' attribute.
   * @see #setElement(String)
   * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getConstructs_Element()
   * @model
   * @generated
   */
  String getElement();

  /**
   * Sets the value of the '{@link de.tubs.isf.guido.dsl.dsl.Constructs#getElement <em>Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' attribute.
   * @see #getElement()
   * @generated
   */
  void setElement(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' attribute.
   * @see #setElements(String)
   * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getConstructs_Elements()
   * @model
   * @generated
   */
  String getElements();

  /**
   * Sets the value of the '{@link de.tubs.isf.guido.dsl.dsl.Constructs#getElements <em>Elements</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elements</em>' attribute.
   * @see #getElements()
   * @generated
   */
  void setElements(String value);

} // Constructs
