/**
 * generated by Xtext 2.19.0
 */
package de.tubs.isf.guido.dsl.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hypothesis</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getName <em>Name</em>}</li>
 *   <li>{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getType <em>Type</em>}</li>
 *   <li>{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getTypes <em>Types</em>}</li>
 *   <li>{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getDescription <em>Description</em>}</li>
 *   <li>{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getDefinition <em>Definition</em>}</li>
 *   <li>{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getConstructs <em>Constructs</em>}</li>
 * </ul>
 *
 * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getHypothesis()
 * @model
 * @generated
 */
public interface Hypothesis extends Type
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getHypothesis_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Parameter)
   * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getHypothesis_Type()
   * @model containment="true"
   * @generated
   */
  Parameter getType();

  /**
   * Sets the value of the '{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Parameter value);

  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference.
   * @see #setTypes(Parameter)
   * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getHypothesis_Types()
   * @model containment="true"
   * @generated
   */
  Parameter getTypes();

  /**
   * Sets the value of the '{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getTypes <em>Types</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Types</em>' containment reference.
   * @see #getTypes()
   * @generated
   */
  void setTypes(Parameter value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference.
   * @see #setDescription(Description)
   * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getHypothesis_Description()
   * @model containment="true"
   * @generated
   */
  Description getDescription();

  /**
   * Sets the value of the '{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getDescription <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' containment reference.
   * @see #getDescription()
   * @generated
   */
  void setDescription(Description value);

  /**
   * Returns the value of the '<em><b>Definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definition</em>' containment reference.
   * @see #setDefinition(Definition)
   * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getHypothesis_Definition()
   * @model containment="true"
   * @generated
   */
  Definition getDefinition();

  /**
   * Sets the value of the '{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getDefinition <em>Definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Definition</em>' containment reference.
   * @see #getDefinition()
   * @generated
   */
  void setDefinition(Definition value);

  /**
   * Returns the value of the '<em><b>Constructs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constructs</em>' containment reference.
   * @see #setConstructs(Constructs)
   * @see de.tubs.isf.guido.dsl.dsl.DslPackage#getHypothesis_Constructs()
   * @model containment="true"
   * @generated
   */
  Constructs getConstructs();

  /**
   * Sets the value of the '{@link de.tubs.isf.guido.dsl.dsl.Hypothesis#getConstructs <em>Constructs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constructs</em>' containment reference.
   * @see #getConstructs()
   * @generated
   */
  void setConstructs(Constructs value);

} // Hypothesis
