/*
 * generated by Xtext 2.20.0
 */
package de.tubs.isf.guido.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DslUiModule extends AbstractDslUiModule {
}
