/*
 * generated by Xtext 2.20.0
 */
package de.tubs.isf.guido.dsl.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class DslScopeProvider extends AbstractDslScopeProvider {

}
