/*
 * generated by Xtext 2.20.0
 */
package de.tubs.isf.guido.dsl.ide

import com.google.inject.Guice
import de.tubs.isf.guido.dsl.DslRuntimeModule
import de.tubs.isf.guido.dsl.DslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DslIdeSetup extends DslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DslRuntimeModule, new DslIdeModule))
	}
	
}
