/**
 * generated by Xtext 2.20.0
 */
package de.tubs.isf.guido.dsl;

import de.tubs.isf.guido.dsl.AbstractDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
