/**
 * generated by Xtext 2.20.0
 */
package de.tubs.isf.guido.dsl.ui.contentassist;

import de.tubs.isf.guido.dsl.ui.contentassist.AbstractDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DslProposalProvider extends AbstractDslProposalProvider {
}
