/**
 * generated by Xtext 2.20.0
 */
package de.tubs.isf.guido.dsl.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class DslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
